[package]
name = "folonet-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tonic = "0.11"
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"