// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `folonet.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

///  定义传入的消息
// @@protoc_insertion_point(message:folonetrpc.StartServerRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct StartServerRequest {
    // message fields
    // @@protoc_insertion_point(field:folonetrpc.StartServerRequest.localEndpoint)
    pub localEndpoint: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:folonetrpc.StartServerRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a StartServerRequest {
    fn default() -> &'a StartServerRequest {
        <StartServerRequest as ::protobuf::Message>::default_instance()
    }
}

impl StartServerRequest {
    pub fn new() -> StartServerRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "localEndpoint",
            |m: &StartServerRequest| { &m.localEndpoint },
            |m: &mut StartServerRequest| { &mut m.localEndpoint },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<StartServerRequest>(
            "StartServerRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for StartServerRequest {
    const NAME: &'static str = "StartServerRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.localEndpoint = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.localEndpoint.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.localEndpoint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.localEndpoint.is_empty() {
            os.write_string(1, &self.localEndpoint)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> StartServerRequest {
        StartServerRequest::new()
    }

    fn clear(&mut self) {
        self.localEndpoint.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static StartServerRequest {
        static instance: StartServerRequest = StartServerRequest {
            localEndpoint: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for StartServerRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("StartServerRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for StartServerRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StartServerRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  定义返回的消息
// @@protoc_insertion_point(message:folonetrpc.StartServerResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct StartServerResponse {
    // message fields
    // @@protoc_insertion_point(field:folonetrpc.StartServerResponse.serverEndpoint)
    pub serverEndpoint: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:folonetrpc.StartServerResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a StartServerResponse {
    fn default() -> &'a StartServerResponse {
        <StartServerResponse as ::protobuf::Message>::default_instance()
    }
}

impl StartServerResponse {
    pub fn new() -> StartServerResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "serverEndpoint",
            |m: &StartServerResponse| { &m.serverEndpoint },
            |m: &mut StartServerResponse| { &mut m.serverEndpoint },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<StartServerResponse>(
            "StartServerResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for StartServerResponse {
    const NAME: &'static str = "StartServerResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.serverEndpoint = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.serverEndpoint.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.serverEndpoint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.serverEndpoint.is_empty() {
            os.write_string(1, &self.serverEndpoint)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> StartServerResponse {
        StartServerResponse::new()
    }

    fn clear(&mut self) {
        self.serverEndpoint.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static StartServerResponse {
        static instance: StartServerResponse = StartServerResponse {
            serverEndpoint: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for StartServerResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("StartServerResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for StartServerResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StartServerResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rfolonet.proto\x12\nfolonetrpc\":\n\x12StartServerRequest\x12$\n\rloc\
    alEndpoint\x18\x01\x20\x01(\tR\rlocalEndpoint\"=\n\x13StartServerRespons\
    e\x12&\n\x0eserverEndpoint\x18\x01\x20\x01(\tR\x0eserverEndpoint2a\n\rSe\
    rverManager\x12P\n\x0bStartServer\x12\x1e.folonetrpc.StartServerRequest\
    \x1a\x1f.folonetrpc.StartServerResponse\"\0B\x0eZ\x0c./folonetrpcJ\xf9\
    \x02\n\x06\x12\x04\0\0\x14\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\
    \x01\x02\x12\x03\x02\0\x13\n\x08\n\x01\x08\x12\x03\x04\0!\n\t\n\x02\x08\
    \x0b\x12\x03\x04\0!\n\x1a\n\x02\x06\0\x12\x04\x07\0\n\x01\x1a\x0e\x20\
    \xe5\xae\x9a\xe4\xb9\x89\xe6\x9c\x8d\xe5\x8a\xa1\n\n\n\n\x03\x06\0\x01\
    \x12\x03\x07\x08\x15\n$\n\x04\x06\0\x02\0\x12\x03\t\x02G\x1a\x17\x20\xe5\
    \xae\x9a\xe4\xb9\x89\xe4\xb8\x80\xe4\xb8\xaaRPC\xe6\x96\xb9\xe6\xb3\x95\
    \n\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\t\x06\x11\n\x0c\n\x05\x06\0\x02\0\
    \x02\x12\x03\t\x13%\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\t0C\n#\n\x02\x04\
    \0\x12\x04\r\0\x0f\x01\x1a\x17\x20\xe5\xae\x9a\xe4\xb9\x89\xe4\xbc\xa0\
    \xe5\x85\xa5\xe7\x9a\x84\xe6\xb6\x88\xe6\x81\xaf\n\n\n\n\x03\x04\0\x01\
    \x12\x03\r\x08\x1a\n\x0b\n\x04\x04\0\x02\0\x12\x03\x0e\x02\x1b\n\x0c\n\
    \x05\x04\0\x02\0\x05\x12\x03\x0e\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03\x0e\t\x16\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0e\x19\x1a\n#\n\x02\
    \x04\x01\x12\x04\x12\0\x14\x01\x1a\x17\x20\xe5\xae\x9a\xe4\xb9\x89\xe8\
    \xbf\x94\xe5\x9b\x9e\xe7\x9a\x84\xe6\xb6\x88\xe6\x81\xaf\n\n\n\n\x03\x04\
    \x01\x01\x12\x03\x12\x08\x1b\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x13\x02\
    \x1c\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\x13\x02\x08\n\x0c\n\x05\x04\
    \x01\x02\0\x01\x12\x03\x13\t\x17\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\
    \x13\x1a\x1bb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(StartServerRequest::generated_message_descriptor_data());
            messages.push(StartServerResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
